services:
  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env-prod
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: money_app
    env_file:
      - .env-prod
    depends_on:
      - db
      - redis
    environment:
      - PYTHONPATH=/app
    command: >
      sh -c "alembic upgrade head &&
             gunicorn src.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    ports:
      - 9000:8000

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379

  celery:
    build:
      context: .
    container_name: app_celery
    command: celery --app=src.tasks.celery_client worker -l INFO
    env_file:
      - .env-prod
    depends_on:
      - redis

  flower:
    build:
      context: .
    container_name: app_flower
    command: celery --app=src.tasks.celery_client flower
    env_file:
      - .env-prod
    depends_on:
      - redis
    ports:
     - 5555:5555


volumes:
  postgres_data: